# Generated by Django 4.1 on 2022-08-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('literal', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('grade', models.IntegerField(default=0)),
                ('stroke_count', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('radical_name', models.CharField(default='', max_length=16)),
                ('jlpt_old', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'kanji',
            },
        ),
        migrations.CreateModel(
            name='KanjidictVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_version', models.IntegerField()),
                ('database_version', models.CharField(max_length=32)),
                ('date_of_creation', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kanjidict_version',
            },
        ),
        migrations.CreateModel(
            name='KanjiRadical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rad_type', models.CharField(max_length=32)),
                ('rad_value', models.IntegerField()),
            ],
            options={
                'db_table': 'kanji_radical',
            },
        ),
        migrations.CreateModel(
            name='Kotoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jmdict_sequence', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'kotoba',
            },
        ),
        migrations.CreateModel(
            name='KotobaKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('information', models.CharField(default=None, max_length=32, null=True)),
                ('priority', models.CharField(default=None, max_length=32, null=True)),
                ('kotoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji', to='dictionary.kotoba')),
            ],
            options={
                'db_table': 'kotoba_kanji',
            },
        ),
        migrations.CreateModel(
            name='KotobaMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(default=None, null=True)),
                ('kotoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictionary.kotoba')),
            ],
            options={
                'db_table': 'kotoba_meaning',
            },
        ),
        migrations.CreateModel(
            name='KotobaReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('information', models.CharField(default=None, max_length=32, null=True)),
                ('priority', models.CharField(default=None, max_length=32, null=True)),
                ('kotoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kana', to='dictionary.kotoba')),
            ],
            options={
                'db_table': 'kotoba_reading',
            },
        ),
        migrations.CreateModel(
            name='KotobaMeaningToReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kana', to='dictionary.kotobameaning')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictionary.kotobareading')),
            ],
        ),
        migrations.CreateModel(
            name='KotobaMeaningToKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictionary.kotobakanji')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji', to='dictionary.kotobameaning')),
            ],
        ),
        migrations.CreateModel(
            name='KotobaMeaningLoanSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=32, null=True)),
                ('word', models.CharField(default=None, max_length=128, null=True)),
                ('type', models.CharField(default=None, max_length=32, null=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_sources', to='dictionary.kotobameaning')),
            ],
            options={
                'db_table': 'kotoba_meaning_loan_source',
            },
        ),
        migrations.CreateModel(
            name='KotobaMeaningField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dictionary.kotobameaning')),
            ],
            options={
                'db_table': 'kotoba_meaning_field',
            },
        ),
        migrations.CreateModel(
            name='KotobaMeaningDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('language', models.CharField(default='eng', max_length=32)),
                ('type', models.CharField(default=None, max_length=32, null=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='dictionary.kotobameaning')),
            ],
            options={
                'db_table': 'kotoba_meaning_definition',
            },
        ),
        migrations.CreateModel(
            name='KotobaKanjiToReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_kana', to='dictionary.kotobakanji')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_kanji', to='dictionary.kotobareading')),
            ],
            options={
                'db_table': 'kotoba_kanji_to_reading',
            },
        ),
        migrations.CreateModel(
            name='KanjiVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_value', models.CharField(max_length=32)),
                ('var_type', models.CharField(max_length=32)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_variant',
            },
        ),
        migrations.CreateModel(
            name='KanjiToRadical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.kanji')),
                ('radical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.kanjiradical')),
            ],
            options={
                'db_table': 'kanji_to_radical',
            },
        ),
        migrations.CreateModel(
            name='KanjiStrokeMiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_count', models.IntegerField()),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_miscounts', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_stroke_miscount',
            },
        ),
        migrations.CreateModel(
            name='KanjiReferenceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=32)),
                ('reference', models.CharField(max_length=32)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_indexes', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_reference_index',
            },
        ),
        migrations.CreateModel(
            name='KanjiReferenceDaikanwajiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=32)),
                ('page', models.CharField(max_length=32)),
                ('kanji_reference_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_diakanwajiten', to='dictionary.kanjireferenceindex')),
            ],
            options={
                'db_table': 'kanji_reference_daikanwajiten',
            },
        ),
        migrations.CreateModel(
            name='KanjiReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(max_length=32)),
                ('reading', models.CharField(max_length=32)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_reading',
            },
        ),
        migrations.CreateModel(
            name='KanjiQueryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_value', models.CharField(max_length=32)),
                ('qc_type', models.CharField(max_length=32)),
                ('skip_misclass', models.CharField(default='', max_length=32)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_codes', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_query_code',
            },
        ),
        migrations.CreateModel(
            name='KanjiMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=16)),
                ('meaning', models.CharField(max_length=128)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_meaning',
            },
        ),
        migrations.CreateModel(
            name='KanjiCodepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_value', models.CharField(max_length=32)),
                ('cp_type', models.CharField(max_length=32)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codepoints', to='dictionary.kanji')),
            ],
            options={
                'db_table': 'kanji_codepoint',
            },
        ),
    ]
