# Generated by Django 4.1 on 2022-08-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kanji",
            fields=[
                (
                    "literal",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("grade", models.IntegerField()),
                ("stroke_count", models.IntegerField()),
                ("frequency", models.IntegerField()),
                ("radical_name", models.CharField(max_length=16)),
                ("jlpt_old", models.IntegerField()),
            ],
            options={
                "db_table": "kanji",
            },
        ),
        migrations.CreateModel(
            name="KanjiRadical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rad_type", models.CharField(max_length=32)),
                ("rad_value", models.IntegerField()),
            ],
            options={
                "db_table": "kanji_radical",
            },
        ),
        migrations.CreateModel(
            name="KanjiVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("var_value", models.CharField(max_length=32)),
                ("var_type", models.CharField(max_length=32)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_variant",
            },
        ),
        migrations.CreateModel(
            name="KanjiToRadical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
                (
                    "radical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanjiradical",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_to_radical",
            },
        ),
        migrations.CreateModel(
            name="KanjiStrokeMiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stroke_count", models.IntegerField()),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_stroke_miscount",
            },
        ),
        migrations.CreateModel(
            name="KanjiReferenceIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_number", models.CharField(max_length=32)),
                ("reference", models.CharField(max_length=32)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_reference_index",
            },
        ),
        migrations.CreateModel(
            name="KanjiReferenceDaikanwajiten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.CharField(max_length=32)),
                ("page", models.CharField(max_length=32)),
                (
                    "kanji_reference_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanjireferenceindex",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_reference_daikanwajiten",
            },
        ),
        migrations.CreateModel(
            name="KanjiReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_type", models.CharField(max_length=32)),
                ("reading", models.CharField(max_length=32)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_reading",
            },
        ),
        migrations.CreateModel(
            name="KanjiQueryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qc_value", models.CharField(max_length=32)),
                ("qc_type", models.CharField(max_length=32)),
                ("skip_misclass", models.CharField(max_length=32)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_query_code",
            },
        ),
        migrations.CreateModel(
            name="KanjiMeaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=16)),
                ("meaning", models.CharField(max_length=128)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_meaning",
            },
        ),
        migrations.CreateModel(
            name="KanjiCodepoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cp_value", models.CharField(max_length=32)),
                ("cp_type", models.CharField(max_length=32)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "kanji_codepoint",
            },
        ),
    ]
