# Generated by Django 4.1 on 2022-08-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanjidictVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_version", models.IntegerField()),
                ("database_version", models.CharField(max_length=32)),
                ("date_of_creation", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "kanjidict_version",
            },
        ),
    ]
