# Generated by Django 4.1 on 2022-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_kanjidictversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanji",
            name="frequency",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kanji",
            name="grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kanji",
            name="jlpt_old",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kanji",
            name="radical_name",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="kanji",
            name="stroke_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="kanjiquerycode",
            name="skip_misclass",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
