# Generated by Django 4.1 on 2022-08-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_alter_kanji_frequency_alter_kanji_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanjiquerycode",
            name="skip_misclass",
            field=models.CharField(default="", max_length=32),
        ),
    ]
