# Use postgres/example user/password credentials
version: "3"

services:
  dictionary:
    build: .
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: example
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
